library(httr)
library(dplyr)
library(here)
library(covidData)

setwd(here())
source("R/get_time_series_data_link.R")
jhu_deaths_data_links <- get_time_series_data_link(measure = "deaths")
save(jhu_deaths_data_links, file = "data/jhu_deaths_data_links.rdata") 
jhu_cases_data_links <- get_time_series_data_link(measure = "cases")
save(jhu_cases_data_links, file = "data/jhu_cases_data_links.rdata")
